### ISSUE TITLE
Could not get access_token

### ISSUE THREAD

**Issue by AaronM44** [mtthidoteu/credit-monzo#1]
Trying to connect to a Barclaycard account but after pasting in the authentication code I get the message "Could not get access_token! There must be a problem with the auth code!" but the code is exactly as shown on screen.

**Comment by mtthidoteu** [comment]
Hi! Sorry for the late response, I've been away for a while. Have you managed to get it working in the end?

**Comment by AaronM44** [comment]
Yeah I did thanks! I must've had a mistake in my secret key. Generated a new one and it worked.

**Comment by mtthidoteu** [comment]
That's great to hear! 

It's my first time doing something like this for people to use so it's great to know at least one person uses it 😁

**Comment by AaronM44** [comment]
It's a really great little app. I'm working on deploying it via an Azure Function to just have it run in the cloud.

**Comment by bee-san** [comment]
![image](https://user-images.githubusercontent.com/10378052/190926049-43684663-9f57-4182-8450-92e7bc35b139.png)
